name: Flatpak

on:
  push:
    tags: [ 'v*' ]

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: flatpak/io.github.salemnopturn.DraughtsMindPro.yml
          bundle: draughtsmind-pro.flatpak
